{
 "title": "Fresh Tomato Devices",
 "description": "Display stats for selected devices on the network\n",
 "time": { "from": "now-5h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "router",
    "label": "Router",
    "query": "show tag values with key = router"
   },
   {
    "name": "device",
    "label": "Device",
    "query": "show tag values with key = device"
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,5m,10m,20m" }
  ]
 },
 "panels": [
  {
   "title": "$device health",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "status",
     "measurement": "hour.vlan2.receive.bytes",
     "query": "SELECT value FROM \"network.up.boolean\" WHERE device =~ /^$device$/ AND router =~ /^$router$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "target": "mem.free.kilobytes"
    },
    {
     "alias": "latency",
     "measurement": "hour.vlan2.receive.bytes",
     "query": "SELECT value FROM \"ping.latency.milliseconds\" WHERE device =~ /^$device$/ AND router =~ /^$router$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "target": "mem.free.kilobytes"
    }
   ]
  },
  {
   "title": "$device bandwidth",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "receive",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "load.uptime",
     "query": "SELECT derivative(value) FROM \"network.receive.bytes\" WHERE router =~ /^$router$/ AND device =~ /^$device$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(mem.total.kilobytes, 3)"
    },
    {
     "alias": "transmit",
     "query": "SELECT derivative(value) FROM \"network.transmit.bytes\" WHERE router =~ /^$router$/ AND device =~ /^$device$/ AND $timeFilter"
    }
   ]
  },
  {
   "title": "$device hourly",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "receive",
     "measurement": "hour.vlan2.receive.bytes",
     "query": "SELECT value FROM \"hour.receive.bytes\" WHERE device =~ /^$device$/ AND router =~ /^$router$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "target": "mem.free.kilobytes"
    },
    {
     "alias": "transmit",
     "measurement": "hour.vlan2.receive.bytes",
     "query": "SELECT value FROM \"hour.transmit.bytes\" WHERE device =~ /^$device$/ AND router =~ /^$router$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "target": "mem.free.kilobytes"
    }
   ]
  },
  {
   "title": "$device daily",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "receive",
     "measurement": "hour.vlan2.receive.bytes",
     "query": "SELECT value FROM \"day.receive.bytes\" WHERE device =~ /^$device$/ AND router =~ /^$router$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "target": "mem.free.kilobytes"
    },
    {
     "alias": "transmit",
     "measurement": "hour.vlan2.receive.bytes",
     "query": "SELECT value FROM \"day.transmit.bytes\" WHERE device =~ /^$device$/ AND router =~ /^$router$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "target": "mem.free.kilobytes"
    }
   ]
  },
  {
   "title": "$device weekly",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "receive",
     "measurement": "hour.vlan2.receive.bytes",
     "query": "SELECT value FROM \"week.receive.bytes\" WHERE device =~ /^$device$/ AND router =~ /^$router$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "target": "mem.free.kilobytes"
    },
    {
     "alias": "transmit",
     "measurement": "hour.vlan2.receive.bytes",
     "query": "SELECT value FROM \"week.transmit.bytes\" WHERE device =~ /^$device$/ AND router =~ /^$router$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "target": "mem.free.kilobytes"
    }
   ]
  },
  {
   "title": "$device monthly",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "receive",
     "measurement": "hour.vlan2.receive.bytes",
     "query": "SELECT value FROM \"month.receive.bytes\" WHERE device =~ /^$device$/ AND router =~ /^$router$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "target": "mem.free.kilobytes"
    },
    {
     "alias": "transmit",
     "measurement": "hour.vlan2.receive.bytes",
     "query": "SELECT value FROM \"month.transmit.bytes\" WHERE device =~ /^$device$/ AND router =~ /^$router$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "target": "mem.free.kilobytes"
    }
   ]
  },
  { "title": "$device", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }, "repeat": "device" },
  {
   "title": "$device bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "receive",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network.vlan2.receive.bytes",
     "query": "SELECT mean(\"value\") FROM (\n  SELECT non_negative_derivative(value, 1s) AS \"value\"\n  FROM \"network.receive.bytes\" \n  WHERE router =~ /^$router$/ AND device =~ /^$device$/ AND $timeFilter\n)\nGROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "target": "aliasByNode(scaleToSeconds(derivative(network.eth1.receive.bytes), 1), 4)"
    },
    {
     "alias": "transmit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network.vlan2.transmit.bytes",
     "query": "SELECT mean(\"value\") FROM (\n  SELECT non_negative_derivative(value, 1s) AS \"value\"\n  FROM \"network.transmit.bytes\" \n  WHERE router =~ /^$router$/ AND device =~ /^$device$/ AND $timeFilter\n)\nGROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "target": "aliasByNode(scaleToSeconds(derivative(network.eth1.transmit.bytes), 1), 4)"
    }
   ]
  },
  {
   "title": "$device health",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "latency",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network.vlan2.receive.bytes",
     "query": "SELECT mean(value) FROM \"ping.latency.milliseconds\" WHERE router =~ /^$router$/ AND device =~ /^$device$/ AND $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "target": "aliasByNode(scaleToSeconds(derivative(network.eth1.receive.bytes), 1), 4)"
    },
    {
     "alias": "status",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network.vlan2.receive.bytes",
     "query": "SELECT value FROM \"network.up.boolean\" WHERE router =~ /^$router$/ AND device =~ /^$device$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "target": "aliasByNode(scaleToSeconds(derivative(network.eth1.receive.bytes), 1), 4)"
    }
   ]
  },
  {
   "title": "$device hourly usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "receive",
     "measurement": "hour.vlan2.receive.bytes",
     "query": "SELECT mean(value) \nFROM \"hour.receive.bytes\" \nWHERE device =~ /^$device$/ AND router =~ /^$router$/ \nAND $timeFilter\nGROUP BY time(10m)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "target": "aliasByNode(scaleToSeconds(derivative(network.eth1.receive.bytes), 1), 4)"
    },
    {
     "alias": "transmit",
     "measurement": "hour.vlan2.transmit.bytes",
     "query": "SELECT mean(value)\nFROM \"hour.transmit.bytes\" \nWHERE device =~ /^$device$/ AND router =~ /^$router$/ \nAND $timeFilter\nGROUP BY time(10m)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "target": "aliasByNode(scaleToSeconds(derivative(network.eth1.transmit.bytes), 1), 4)"
    }
   ]
  },
  {
   "title": "$device daily usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "receive",
     "measurement": "day.vlan2.receive.bytes",
     "query": "SELECT mean(value) \nFROM \"day.receive.bytes\" \nWHERE device =~ /^$device$/ AND router =~ /^$router$/ \nAND $timeFilter\nGROUP BY time(2h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "router::tag", "operator": "=~", "value": "/^$router$/" }
     ],
     "target": "aliasByNode(scaleToSeconds(derivative(network.eth1.receive.bytes), 1), 4)"
    },
    {
     "alias": "transmit",
     "measurement": "day.vlan2.transmit.bytes",
     "query": "SELECT mean(value)\nFROM \"day.transmit.bytes\" \nWHERE device =~ /^$device$/ \nAND router =~ /^$router$/ \nAND $timeFilter\nGROUP BY time(2h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "target": "aliasByNode(scaleToSeconds(derivative(network.eth1.transmit.bytes), 1), 4)"
    }
   ]
  },
  {
   "title": "$device weekly usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "receive",
     "measurement": "week.vlan2.receive.bytes",
     "query": "SELECT mean(value) \nFROM \"week.receive.bytes\" \nWHERE device =~ /^$device$/ \nAND router =~ /^$router$/ \nAND $timeFilter\nGROUP BY time(12h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "target": "aliasByNode(scaleToSeconds(derivative(network.eth1.receive.bytes), 1), 4)"
    },
    {
     "alias": "transmit",
     "measurement": "week.vlan2.transmit.bytes",
     "query": "SELECT mean(value)\nFROM \"week.transmit.bytes\" \nWHERE device =~ /^$device$/ \nAND router =~ /^$router$/ \nAND $timeFilter\nGROUP BY time(12h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "target": "aliasByNode(scaleToSeconds(derivative(network.eth1.transmit.bytes), 1), 4)"
    }
   ]
  },
  {
   "title": "$device monthly usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "receive",
     "measurement": "month.vlan2.receive.bytes",
     "query": "SELECT mean(value) \nFROM \"month.receive.bytes\" \nWHERE device =~ /^$device$/ \nAND router =~ /^$router$/ \nAND $timeFilter\nGROUP BY time(2d)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "target": "aliasByNode(scaleToSeconds(derivative(network.eth1.receive.bytes), 1), 4)"
    },
    {
     "alias": "transmit",
     "measurement": "month.vlan2.transmit.bytes",
     "query": "SELECT mean(value) \nFROM \"month.transmit.bytes\" \nWHERE device =~ /^$device$/ \nAND router =~ /^$router$/ \nAND $timeFilter\nGROUP BY time(2d)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "target": "aliasByNode(scaleToSeconds(derivative(network.eth1.transmit.bytes), 1), 4)"
    }
   ]
  }
 ]
}