{
 "title": "Fresh Tomato Router",
 "description": "Display metrics gathered from a fresh tomato router\n",
 "tags": [
  "router",
  "tomato",
  "bandwidth",
  "freshtomato"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "router",
    "label": "Router",
    "query": "show tag values with key = router"
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,5m,10m,20m" },
   { "name": "wan", "query": "vlan2" },
   { "name": "lan", "query": "br0" }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "load.uptime",
     "query": "SELECT \"value\" FROM \"load.uptime\" WHERE router::tag =~ /(^$router$|\\s*)/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "router::tag", "operator": "=~", "value": "/^$router$/" }
     ],
     "target": "aliasByNode(mem.total.kilobytes, 3)"
    }
   ]
  },
  {
   "title": "WAN receive",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "load.uptime",
     "query": "SELECT non_negative_derivative(value) FROM \"network.$wan.receive.bytes\"  WHERE router =~ /(^$router$|\\s*)/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(mem.total.kilobytes, 3)"
    }
   ]
  },
  {
   "title": "LAN receive",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "load.uptime",
     "query": "SELECT non_negative_derivative(value) FROM \"network.$lan.receive.bytes\" WHERE router =~ /(^$router$|\\s*)/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(mem.total.kilobytes, 3)"
    }
   ]
  },
  {
   "title": "Hourly download",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "hour.vlan2.receive.bytes",
     "query": "SELECT value FROM \"hour.receive.bytes\" WHERE router =~ /^$router$/ AND device =~ /^$wan$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "target": "mem.free.kilobytes"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "cpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temp.cpu.degrees",
     "query": "SELECT value FROM \"temp.cpu.degrees\" WHERE router =~ /(^$router$|\\s*)/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "temp.cpu.degrees"
    },
    {
     "alias": "eth1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temp.cpu.degrees",
     "query": "SELECT value FROM \"temp.eth1.degrees\" WHERE router =~ /(^$router$|\\s*)/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "temp.cpu.degrees"
    },
    {
     "alias": "eth2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temp.cpu.degrees",
     "query": "SELECT value FROM \"temp.eth2.degrees\" WHERE router =~ /(^$router$|\\s*)/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "temp.cpu.degrees"
    }
   ]
  },
  {
   "title": "2.4GHz receive",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "load.uptime",
     "query": "SELECT non_negative_derivative(value) FROM \"network.eth1.receive.bytes\" WHERE router =~ /(^$router$|\\s*)/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(mem.total.kilobytes, 3)"
    }
   ]
  },
  {
   "title": "5GHz receive",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "load.uptime",
     "query": "SELECT non_negative_derivative(value) FROM \"network.eth2.receive.bytes\" WHERE router =~ /(^$router$|\\s*)/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(mem.total.kilobytes, 3)"
    }
   ]
  },
  {
   "title": "speedtest download",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "load.uptime",
     "query": "SELECT value FROM \"speedtest.download\" WHERE router =~ /(^$router$|\\s*)/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(mem.total.kilobytes, 3)"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "client.count",
     "query": "SELECT value FROM \"client.count\" WHERE router =~ /(^$router$|\\s*)/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "sumSeries(wireless.*.clients)"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "WAN transmit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "load.uptime",
     "query": "SELECT non_negative_derivative(value) FROM \"network.$wan.transmit.bytes\" WHERE router =~ /(^$router$|\\s*)/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(mem.total.kilobytes, 3)"
    }
   ]
  },
  {
   "title": "LAN transmit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "load.uptime",
     "query": "SELECT \n    non_negative_derivative(value) \nFROM \n    \"network.$lan.transmit.bytes\" \nWHERE \n    router =~ /(^$router$|\\s*)/ AND \n    $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(mem.total.kilobytes, 3)"
    }
   ]
  },
  {
   "title": "Daily download",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem.active.kilobytes",
     "query": "SELECT value FROM \"day.receive.bytes\" WHERE router =~ /^$router$/ AND device =~ /^$wan$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "256000 -" ], "type": "math" }
      ]
     ],
     "target": "mem.free.kilobytes"
    }
   ]
  },
  {
   "title": "2.4GHz transmit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "load.uptime",
     "query": "SELECT non_negative_derivative(value) FROM \"network.eth1.transmit.bytes\" WHERE router =~ /(^$router$|\\s*)/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(mem.total.kilobytes, 3)"
    }
   ]
  },
  {
   "title": "5GHz transmit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "load.uptime",
     "query": "SELECT non_negative_derivative(value) FROM \"network.eth2.transmit.bytes\" WHERE router =~ /(^$router$|\\s*)/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(mem.total.kilobytes, 3)"
    }
   ]
  },
  {
   "title": "speedtest upload",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "load.uptime",
     "query": "SELECT value FROM \"speedtest.upload\" WHERE router =~ /(^$router$|\\s*)/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(mem.total.kilobytes, 3)"
    }
   ]
  },
  {
   "title": "Ping google",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "ping.google.latency",
     "query": "SELECT value FROM \"ping.google.latency\" WHERE router =~ /(^$router$|\\s*)/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "target": "temp.cpu.degrees"
    }
   ]
  },
  {
   "title": "WAN ($wan) Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "receive",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network.vlan2.receive.bytes",
     "query": "SELECT mean(\"value\")  FROM (\n  SELECT non_negative_derivative(value, 1s) AS \"value\"\n  FROM \"network.$wan.receive.bytes\" \n  WHERE router =~ /(^$router$|\\s*)/ AND $timeFilter\n)\nGROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "target": "aliasByNode(scaleToSeconds(derivative(network.eth1.receive.bytes), 1), 4)"
    },
    {
     "alias": "transmit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network.vlan2.transmit.bytes",
     "query": "SELECT mean(\"value\")  FROM (\n  SELECT non_negative_derivative(value, 1s) AS \"value\"\n  FROM \"network.$wan.transmit.bytes\" \n  WHERE router =~ /(^$router$|\\s*)/ AND $timeFilter\n)\nGROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "target": "aliasByNode(scaleToSeconds(derivative(network.eth1.transmit.bytes), 1), 4)"
    }
   ]
  },
  {
   "title": "LAN ($lan) Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "receive",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network.br0.receive.bytes",
     "query": "SELECT mean(\"value\")  FROM (\n  SELECT non_negative_derivative(value, 1s) AS \"value\"\n  FROM \"network.$lan.receive.bytes\" \n  WHERE router =~ /(^$router$|\\s*)/ AND $timeFilter\n)\nGROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "target": "aliasByNode(scaleToSeconds(derivative(network.br0.receive.bytes), 1), 4)"
    },
    {
     "alias": "transmit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network.br0.transmit.bytes",
     "query": "SELECT mean(\"value\")  FROM (\n  SELECT non_negative_derivative(value, 1s) AS \"value\"\n  FROM \"network.$lan.transmit.bytes\" \n  WHERE router =~ /(^$router$|\\s*)/ AND $timeFilter\n)\nGROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "target": "aliasByNode(scaleToSeconds(derivative(network.br0.transmit.bytes), 1), 4)"
    }
   ]
  },
  {
   "title": "WAN ($wan) Hourly Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "receive",
     "measurement": "hour.vlan2.receive.bytes",
     "query": "SELECT mean(value) \nFROM \"hour.receive.bytes\" \nWHERE router=~ /^$router$/ and device =~ /^$wan$/ \nAND $timeFilter \ngroup by time(10m)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "target": "aliasByNode(scaleToSeconds(derivative(network.eth1.receive.bytes), 1), 4)"
    },
    {
     "alias": "transmit",
     "measurement": "hour.vlan2.transmit.bytes",
     "query": "SELECT mean(value) \nFROM \"hour.transmit.bytes\" \nWHERE router=~ /^$router$/ and device =~ /^$wan$/ \nAND $timeFilter  \ngroup by time(10m)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "target": "aliasByNode(scaleToSeconds(derivative(network.eth1.transmit.bytes), 1), 4)"
    }
   ]
  },
  {
   "title": "WAN ($wan) Daily Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "receive",
     "measurement": "day.vlan2.receive.bytes",
     "query": "SELECT mean(value)\n FROM \"day.receive.bytes\" \nWHERE router=~ /^$router$/ and device =~ /^$wan$/ AND $timeFilter\ngroup by time(2h)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "router::tag", "operator": "=~", "value": "/^$router$/" }
     ],
     "target": "aliasByNode(scaleToSeconds(derivative(network.eth1.receive.bytes), 1), 4)"
    },
    {
     "alias": "transmit",
     "measurement": "day.vlan2.transmit.bytes",
     "query": "SELECT mean(value)\n FROM \"day.transmit.bytes\" \nWHERE router=~ /^$router$/ and device =~ /^$wan$/ AND $timeFilter\nGROUP BY time(2h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "target": "aliasByNode(scaleToSeconds(derivative(network.eth1.transmit.bytes), 1), 4)"
    }
   ]
  },
  {
   "title": "WAN ($wan) Weekly Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "receive",
     "measurement": "week.vlan2.receive.bytes",
     "query": "SELECT mean(value) \nFROM \"week.receive.bytes\" \nWHERE router=~ /^$router$/ \nand device =~ /^$wan$/ \nAND $timeFilter \nGROUP BY time(12h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "target": "aliasByNode(scaleToSeconds(derivative(network.eth1.receive.bytes), 1), 4)"
    },
    {
     "alias": "transmit",
     "measurement": "week.vlan2.transmit.bytes",
     "query": "SELECT mean(value)\nFROM \"week.transmit.bytes\" \nWHERE router=~ /^$router$/ and device =~ /^$wan$/ \nAND $timeFilter\nGROUP BY time(12h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "target": "aliasByNode(scaleToSeconds(derivative(network.eth1.transmit.bytes), 1), 4)"
    }
   ]
  },
  {
   "title": "WAN ($wan) Monthly Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "receive",
     "measurement": "month.vlan2.receive.bytes",
     "query": "SELECT mean(value)\nFROM \"month.receive.bytes\" \nWHERE router=~ /^$router$/ \nAND device =~ /^$wan$/ \nAND $timeFilter\nGROUP BY time(2d)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "target": "aliasByNode(scaleToSeconds(derivative(network.eth1.receive.bytes), 1), 4)"
    },
    {
     "alias": "transmit",
     "measurement": "month.vlan2.transmit.bytes",
     "query": "SELECT mean(value) \nFROM \"month.transmit.bytes\" \nWHERE router=~ /^$router$/ and device =~ /^$wan$/ \nAND $timeFilter\nGROUP BY time(2d)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "target": "aliasByNode(scaleToSeconds(derivative(network.eth1.transmit.bytes), 1), 4)"
    }
   ]
  },
  {
   "title": "Wireless 5GHz (eth2) Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "receive",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network.eth2.receive.bytes",
     "query": "SELECT mean(\"value\")  FROM (\n  SELECT non_negative_derivative(value, 1s) AS \"value\"\n  FROM \"network.eth2.receive.bytes\" \n  WHERE router =~ /(^$router$|\\s*)/ AND $timeFilter\n)\nGROUP BY time($interval) fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "target": "aliasByNode(scaleToSeconds(derivative(network.ath1.receive.bytes), 1), 4)"
    },
    {
     "alias": "transmit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network.eth2.transmit.bytes",
     "query": "SELECT mean(\"value\")  FROM (\n  SELECT non_negative_derivative(value, 1s) AS \"value\"\n  FROM \"network.eth2.transmit.bytes\" \n  WHERE router =~ /(^$router$|\\s*)/ AND $timeFilter\n)\nGROUP BY time($interval) fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "target": "aliasByNode(scaleToSeconds(derivative(network.ath1.transmit.bytes), 1), 4)"
    }
   ]
  },
  {
   "title": "Wireless 2.4GHz (eth1) Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "receive",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network.eth1.receive.bytes",
     "query": "SELECT mean(\"value\")  FROM (\n  SELECT non_negative_derivative(value, 1s) AS \"value\"\n  FROM \"network.eth1.receive.bytes\" \n  WHERE router =~ /(^$router$|\\s*)/ AND $timeFilter\n)\nGROUP BY time($interval) fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "target": "aliasByNode(scaleToSeconds(derivative(network.eth0.receive.bytes), 1), 4)"
    },
    {
     "alias": "transmit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "network.eth1.transmit.bytes",
     "query": "SELECT mean(\"value\")  FROM (\n  SELECT non_negative_derivative(value, 1s) AS \"value\"\n  FROM \"network.eth1.transmit.bytes\" \n  WHERE router =~ /(^$router$|\\s*)/ AND $timeFilter\n)\nGROUP BY time($interval) fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "target": "aliasByNode(scaleToSeconds(derivative(network.eth0.transmit.bytes), 1), 4)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "iowait",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu.iowait",
     "query": "SELECT mean(\"value\") FROM (\n  SELECT non_negative_derivative(value, 1s) AS \"value\"\n  FROM \"cpu.iowait\" \n  WHERE router =~ /(^$router$|\\s*)/ AND $timeFilter\n)\nGROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ]
    },
    {
     "alias": "user",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu.user",
     "query": "SELECT mean(\"value\") FROM (\n  SELECT non_negative_derivative(value, 1s) AS \"value\"\n  FROM \"cpu.user\" \n  WHERE router =~ /(^$router$|\\s*)/ AND $timeFilter\n)\nGROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ]
    },
    {
     "alias": "system",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu.system",
     "query": "SELECT mean(\"value\") FROM (\n  SELECT non_negative_derivative(value, 1s) AS \"value\"\n  FROM \"cpu.system\" \n  WHERE router =~ /(^$router$|\\s*)/ AND $timeFilter\n)\nGROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ]
    },
    {
     "alias": "softirq",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu.softirq",
     "query": "SELECT mean(\"value\") FROM (\n  SELECT non_negative_derivative(value, 1s) AS \"value\"\n  FROM \"cpu.softirq\" \n  WHERE router =~ /(^$router$|\\s*)/ AND $timeFilter\n)\nGROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ]
    },
    {
     "alias": "nice",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu.nice",
     "query": "SELECT mean(\"value\") FROM (\n  SELECT non_negative_derivative(value, 1s) AS \"value\"\n  FROM \"cpu.nice\" \n  WHERE router =~ /(^$router$|\\s*)/ AND $timeFilter\n)\nGROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ]
    },
    {
     "alias": "irq",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu.irq",
     "query": "SELECT mean(\"value\") FROM (\n  SELECT non_negative_derivative(value, 1s) AS \"value\"\n  FROM \"cpu.irq\" \n  WHERE router =~ /(^$router$|\\s*)/ AND $timeFilter\n)\nGROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "load 1m",
     "measurement": "temp.cpu.degrees",
     "query": "SELECT mean(\"value\") FROM \"load.load_one.number\" WHERE router =~ /(^$router$|\\s*)/ AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "router::tag", "operator": "=~", "value": "/^$router$/" }
     ],
     "target": "aliasByNode(temp.*.degrees, 3)"
    },
    {
     "alias": "load 5m",
     "measurement": "temp.eth1.degrees",
     "query": "SELECT mean(\"value\") FROM \"load.load_five.number\" WHERE router =~ /(^$router$|\\s*)/ AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "target": "aliasByNode(temp.*.degrees, 3)"
    },
    {
     "alias": "load 15m",
     "measurement": "temp.eth2.degrees",
     "query": "SELECT mean(\"value\") FROM \"load.load_fifteen.number\" WHERE router =~ /(^$router$|\\s*)/ AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "target": "aliasByNode(temp.*.degrees, 3)"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "cpu",
     "measurement": "temp.cpu.degrees",
     "query": "SELECT mean(\"value\") FROM \"temp.cpu.degrees\" WHERE router =~ /(^$router$|\\s*)/ AND $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "router::tag", "operator": "=~", "value": "/^$router$/" }
     ],
     "target": "aliasByNode(temp.*.degrees, 3)"
    },
    {
     "alias": "eth1",
     "measurement": "temp.eth1.degrees",
     "query": "SELECT mean(\"value\") FROM \"temp.eth1.degrees\" WHERE router =~ /(^$router$|\\s*)/ AND $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "target": "aliasByNode(temp.*.degrees, 3)"
    },
    {
     "alias": "eth2",
     "measurement": "temp.eth2.degrees",
     "query": "SELECT mean(\"value\") FROM \"temp.eth2.degrees\" WHERE router =~ /(^$router$|\\s*)/ AND $timeFilter group by time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "target": "aliasByNode(temp.*.degrees, 3)"
    }
   ]
  },
  {
   "title": "Disk Usage (/opt)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Mb used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "disk./opt.used",
     "query": "SELECT value FROM \"disk./opt.used\" WHERE router::tag =~ /(^$router$|\\s*)/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "% used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "disk./opt.percent",
     "query": "SELECT value FROM \"disk./opt.percent\" WHERE router::tag =~ /(^$router$|\\s*)/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem.used.kilobytes",
     "query": "SELECT value FROM \"mem.used.kilobytes\" WHERE router::tag =~ /(^$router$|\\s*)/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(scale(mem.used.bytes, 0.0010), 3)"
    },
    {
     "alias": "buffers",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem.buffers.kilobytes",
     "query": "SELECT value FROM \"mem.buffers.kilobytes\" WHERE router::tag =~ /(^$router$|\\s*)/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(mem.buffers.kilobytes, 3)"
    },
    {
     "alias": "cached",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem.cached.kilobytes",
     "query": "SELECT value FROM \"mem.cached.kilobytes\" WHERE router::tag =~ /(^$router$|\\s*)/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(mem.cached.kilobytes, 3)"
    },
    {
     "alias": "active",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem.active.kilobytes",
     "query": "SELECT value FROM \"mem.active.kilobytes\" WHERE router::tag =~ /(^$router$|\\s*)/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(mem.active.kilobytes, 3)"
    },
    {
     "alias": "inactive",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem.inactive.kilobytes",
     "query": "SELECT value FROM \"mem.inactive.kilobytes\" WHERE router::tag =~ /(^$router$|\\s*)/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(mem.inactive.kilobytes, 3)"
    },
    {
     "alias": "free",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem.free.kilobytes",
     "query": "SELECT value FROM \"mem.free.kilobytes\" WHERE router::tag =~ /(^$router$|\\s*)/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(mem.inactive.kilobytes, 3)"
    },
    {
     "alias": "total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem.total.kilobytes",
     "query": "SELECT value FROM \"mem.total.kilobytes\" WHERE router::tag =~ /(^$router$|\\s*)/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(mem.inactive.kilobytes, 3)"
    }
   ]
  },
  {
   "title": "Packet Loss",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "loss",
     "measurement": "ping.google.packetloss.percent",
     "query": "SELECT value FROM \"ping.google.packetloss.percent\" WHERE router =~ /(^$router$|\\s*)/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "target": "aliasByNode(ping.*.packetloss.percent, 3)"
    }
   ]
  },
  {
   "title": "speedtest",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "download",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping.google.latency",
     "query": "SELECT \"value\" FROM \"speedtest.download\" WHERE router::tag =~ /(^$router$|\\s*)/ AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(ping.*.latency, 3)"
    },
    {
     "alias": "upload",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping.google.latency",
     "query": "SELECT \"value\" FROM \"speedtest.upload\" WHERE router::tag =~ /(^$router$|\\s*)/ AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(ping.*.latency, 3)"
    }
   ]
  },
  {
   "title": "Active IP Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "icmp",
     "measurement": "connections.icmp.number",
     "query": "SELECT mean(\"value\") FROM \"connections.icmp.number\" WHERE router =~ /(^$router$|\\s*)/ AND $timeFilter  GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "target": "aliasByNode(connections.total, 3)"
    },
    {
     "alias": "tcp",
     "measurement": "connections.tcp.number",
     "query": "SELECT mean(\"value\") FROM \"connections.tcp.number\" WHERE router =~ /(^$router$|\\s*)/ AND $timeFilter  GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "target": "aliasByNode(connections.total, 3)"
    },
    {
     "alias": "udp",
     "measurement": "connections.udp.number",
     "query": "SELECT mean(\"value\") FROM \"connections.udp.number\" WHERE router =~ /(^$router$|\\s*)/ AND $timeFilter  GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "target": "aliasByNode(connections.total, 3)"
    },
    {
     "alias": "total",
     "measurement": "connections.total",
     "query": "SELECT mean(\"value\") FROM \"connections.total\" WHERE router =~ /(^$router$|\\s*)/ AND $timeFilter  GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "target": "aliasByNode(connections.total, 3)"
    }
   ]
  },
  {
   "title": "Ping latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "google",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping.google.latency",
     "query": "SELECT mean(\"value\") FROM \"ping.google.latency\" WHERE router::tag =~ /(^$router$|\\s*)/ AND $timeFilter  GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "target": "aliasByNode(ping.*.latency, 3)"
    }
   ]
  }
 ]
}